#import "../../config/acronyms.typ": *
== Formula Student
Formula Student ist ein internationaler Ingenieurswettbewerb, bei dem Studierendenteams weltweit einsitzige Rennfahrzeuge im Formel-Stil konzipieren, entwickeln, bauen und gegeneinander antreten. Die Wurzeln des Wettbewerbs liegen in der 1981 von der Society of Automotive Engineers (SAE) ins Leben gerufenen Formula SAE in den USA @SAE_FSAE_About, @IMechE_FS_About. Im Jahr 1998 wurde der Wettbewerb in Kooperation mit der Institution of Mechanical Engineers (IMechE) auf Europa ausgeweitet, wo er seither unter dem Namen Formula Student ausgetragen wird @IMechE_FS_About. Formula Student Germany (FSG), eine der weltweit renommiertesten Austragungen des Wettbewerbs, fand erstmals 2006 am Hockenheimring statt. Mit der ersten rein elektrischen Klasse im Jahr 2010 und der Einführung der autonomen Klasse im Jahr 2017 hat sich FSG stetig weiterentwickelt und gilt heute als internationaler Vorreiter im studentischen Rennsport @FSG_About.

Das Grundprinzip des Wettbewerbs ist, dass der Sieg nicht allein durch die schnellste Rundenzeit errungen wird, sondern durch das beste Gesamtpaket aus Konstruktion, Fahrzeugleistung sowie wirtschaftlicher und vertrieblicher Planung. Die Teams treten in statischen und dynamischen Disziplinen an, darunter Engineering Design, Cost and Manufacturing, Business Plan Presentation sowie die fahrdynamischen Veranstaltungen Acceleration, Skidpad, Autocross und Endurance @FSG_About. Das Endurance-Event erstreckt sich über eine Distanz von 22 Kilometern und stellt dabei die Zuverlässigkeit und Gesamtperformance des Fahrzeugs unter Langzeitbedingungen auf die Probe @FSG_About.
=== Driverless Cup
Im Jahr 2017 führte FSG als weltweit erster Formula Student Wettbewerb eine eigene Klasse für autonome Fahrzeuge ein: die Formula Student Driverless (FSD) @FSG_About, @FSG_DV2017_Announcement. Die Fahrzeuge müssen dabei sowohl manuell als auch vollständig autonom fahren können, wobei die technischen Basisanforderungen der bestehenden Formula Student Electric Klasse erfüllt sein müssen @FSG_DV2017_Announcement.

Ab dem Jahr 2022 wurde die FSD als eigenständige Klasse aufgelöst und die Driverless-Funktionalität vollständig in die Elektroklasse integriert @FSG_FSD_Teams. Seitdem können Electric-Teams zusätzlich am Driverless Cup (DC) teilnehmen, einem separaten Wertungssystem innerhalb von FSG, das gezielt Teams mit vollständig autonomiefähigen Fahrzeugen anspricht. Der Driverless Cup umfasst zwei zusätzliche dynamische Disziplinen, die ausschließlich ohne Fahrer absolviert werden: den autonomen Autocross sowie den autonomen Trackdrive @FSG_About. Der Trackdrive, der mit der höchsten Punktzahl aller Driverless-Disziplinen gewichtet ist, besteht aus zehn Runden auf demselben Rundkurs, den das Fahrzeug vollständig autonom und ohne menschlichen Eingriff absolvieren muss @FSG_About, @fsgrules2026. Der DC richtet sich gemäß FSG ausdrücklich an Teams, deren Fahrzeug bereits in der Lage ist, sowohl autonomen Autocross als auch autonomen Trackdrive zu absolvieren, und soll den technologischen Fortschritt der Driverless-Teams anerkennen sowie ihre Weiterentwicklung vorantreiben @FSG_FSD_Teams.
