#import "../../config/acronyms.typ": *
#include "../../config/config.typ"

== Entwicklungssoftware
=== CAD-Software
Für die Konstruktion und Modellierung aller mechanischen Komponenten des #acro("DVPC") wird Siemens NX als Primäranwendung eingesetzt. Die Auswahl von NX begründet sich auf zwei wesentlichen Faktoren: Zum einen hat sich Siemens NX bereits als etabliertes Standard-#acro("CAD")-System im Verein DHBW Engineering bewährt und wird von mehreren Teams erfolgreich für komplexe Konstruktionsaufgaben genutzt. Zum anderen verfügt der Autor durch vorangegangene Projekte über umfangreiche praktische Erfahrung mit dieser Software, was eine effiziente und sichere Umsetzung der Konstruktionsziele ermöglicht. Die umfangreichen Funktionalitäten von NX ermöglichen eine präzise Auslegung aller Komponenten des #acro("DVPC") unter Berücksichtigung der spezifischen Anforderungen des Gesamtfahrzeugs @nxsiemens, @nxSchulung.
=== Elektronik-Design-Software
Für die Planung und den Entwurf von #acro("PCB")s wird Horizon EDA als primäres Werkzeug eingesetzt. Bei Horizon EDA handelt es sich um ein open-source Electronic Design Automation-Paket, das den vollständigen Workflow von der Schemaerstellung bis zum Gerber-Export für die Fertigung abdeckt @horizoneda. Die Auswahl von Horizon EDA begründet sich auf zwei wesentlichen Faktoren: Zum einen ist die Software bereits im Verein etabliert und wird für die Entwicklung vereinsinterner Platinen genutzt, wodurch eine gemeinsame Bauteilbibliothek gepflegt und geteilt werden kann. Zum anderen arbeitet der Schemaeditor netlistbasiert, was bedeutet, dass die Software über Netze und deren Verbindungen informiert ist und Fehler beim Zusammenführen von Leitungen erkennt. Über die integrierte Design Rule Check (DRC)-Funktionalität lassen sich Designverstöße vor der Fertigung lokalisieren und beheben @horizoneda. Der Funktionsumfang der Software, darunter ein interaktiver Router sowie eine 3D-Vorschau, deckt die Anforderungen der im Rahmen dieser Arbeit entwickelten Platinen ab.
=== Simulationstools
Für die Durchführung der #acro("CFD")-Simulationen zur Auslegung und Optimierung des Kühlkörpers wird Simcenter STAR-CCM+ eingesetzt. Bei Simcenter STAR-CCM+ handelt es sich um eine kommerzielle Multiphysik-Simulationssoftware von Siemens Digital Industries Software, die einen vollständig integrierten Workflow von der Geometrieaufbereitung über die Vernetzung bis zur Ergebnisauswertung in einer einzigen Benutzeroberfläche bereitstellt @starccm. Die Auswahl von STAR-CCM+ begründet sich auf zwei wesentlichen Faktoren: Zum einen ist die Software im Verein DHBW Engineering verfügbar und wird in verschiedenen Teamprojekten bereits erfolgreich für strömungsmechanische Analysen eingesetzt. Zum anderen ermöglicht die Software durch ihre automatisierten Vernetzungsalgorithmen und die umfangreichen Turbulenzmodelle eine präzise Simulation des konvektiven Wärmeübergangs in Flüssigkeitskühlkreisläufen @starccm. 