#import "../../config/acronyms.typ": *
#import "../../config/functions.typ": *
#include "../../config/config.typ"

== Vorgehensmodell<sec:vorgehensmodell>

Die Entwicklung des Datenmodells umfasst mehrere aufeinander aufbauende Tätigkeiten, von der Analyse des Systemkontexts und der Stakeholder über die Festlegung der Anforderungen und die anschließende Auswahl und Aufbereitung der bereitgestellten Gerätedaten bis hin zur Umsetzung des Mappings und dessen Validierung. Um diesen Ablauf nachvollziehbar zu strukturieren, wird ein Vorgehensmodell zugrunde gelegt. Ein solches Modell unterteilt den Entwicklungsprozess in definierte Phasen und legt deren Reihenfolge sowie die zwischen ihnen bestehenden Abhängigkeiten fest @src:sommerville2016. Im Folgenden werden mit dem Wasserfallmodell und dem darauf aufbauenden V-Modell zwei etablierte Vorgehensmodelle vorgestellt und anschließend begründet, welches Modell sich für die vorliegende Arbeit eignet.

Das Wasserfallmodell zählt zu den ältesten Vorgehensmodellen der Softwaretechnik und geht in seiner ursprünglichen Beschreibung auf Royce zurück @src:royce1970. Es gliedert die Entwicklung in aufeinanderfolgende Phasen, die typischerweise die Anforderungsanalyse, den Entwurf, die Implementierung, den Test und den Betrieb umfassen. Diese Phasen werden streng sequenziell durchlaufen, wobei eine Phase erst begonnen wird, wenn die vorhergehende abgeschlossen ist @src:sommerville2016. Der wesentliche Vorteil dieses Modells liegt in seiner Einfachheit und klaren Struktur, weshalb es sich vor allem bei stabilen und von Beginn an vollständig bekannten Anforderungen eignet @src:sommerville2016. Als nachteilig erweist sich jedoch, dass eine Überprüfung der Ergebnisse erst spät im Prozess erfolgt und Fehler aus frühen Phasen häufig erst im abschließenden Test sichtbar werden. Notwendige Rücksprünge in vorgelagerte Phasen sind dadurch mit hohem Aufwand verbunden @src:royce1970.

Das V-Modell erweitert das Wasserfallmodell, indem es jeder konstruktiven Phase eine korrespondierende prüfende Phase gegenüberstellt @src:ludewig2023. Grafisch werden die Phasen dabei in Form eines „V" angeordnet: Der absteigende, linke Ast beschreibt die zunehmende Detaillierung von den Anforderungen über den System- bis zum Feinentwurf, während der aufsteigende, rechte Ast die schrittweise Integration und Prüfung abbildet. Jeder Prüfebene ist dabei eine Spezifikationsebene des linken Astes zugeordnet, gegen die verifiziert und validiert wird @src:ludewig2023. Ein charakteristisches Merkmal des V-Modells besteht darin, dass die zugehörigen Testfälle bereits parallel zur jeweiligen Spezifikationsphase entworfen werden und nicht erst nach der Implementierung. Insbesondere für die Entwicklung mechatronischer und eingebetteter Systeme, in denen Hardware- und Softwareanteile zusammenwirken, ist das V-Modell als Entwicklungsmethodik etabliert und in der VDI-Richtlinie 2206 beschrieben @src:vdi2206. In ihrer aktuellen Fassung erweitert diese Richtlinie das V-Modell ausdrücklich auf cyber-physische Systeme, also auf vernetzte Systeme, die physische Komponenten über Kommunikationsschnittstellen mit informationsverarbeitenden Funktionen verbinden @src:vdi2206.

Für die vorliegende Arbeit wird das V-Modell als Vorgehensmodell gewählt. Ausschlaggebend ist der stark prüfungsorientierte Charakter der Aufgabenstellung: Aus der Analyse des Systemkontexts und der Stakeholder werden die Anforderungen an das Datenmodell abgeleitet, aus denen wiederum die Testfälle entworfen werden. Die bereitgestellten Gerätedaten werden erst im Rahmen der Entwicklung ausgewertet, um die für die Anforderungen relevanten Datenpunkte auszuwählen und im Datenmodell abzubilden. Das so entwickelte Datenmodell wird abschließend anhand der Testfälle am Hardware-Testaufbau validiert. Diese Zuordnung von Anforderungen und zugehörigen Prüfschritten entspricht unmittelbar der Struktur des V-Modells und wird in den Kapiteln zu den Anforderungen und zur Validierung wieder aufgegriffen. Da die Arbeit zudem sowohl Hardwarekomponenten wie die #acro("ECPD") und das SENTRON Powercenter als auch die softwareseitige Modellierung in Desigo CC umfasst und diese Komponenten über Kommunikationsschnittstellen miteinander vernetzt sind, ordnet sich das Vorhaben in den Bereich der cyber-physischen Systeme ein, für den die aktuelle Richtlinienfassung das V-Modell ausdrücklich vorsieht @src:vdi2206. Einschränkend ist anzumerken, dass die eigentliche Umsetzung des Datenmodells nicht rein sequenziell, sondern iterativ und testgetrieben erfolgt, da das Mapping fortlaufend anhand der Testfälle überprüft und verfeinert wird. Das V-Modell dient in dieser Arbeit daher als übergeordneter Rahmen, innerhalb dessen die Entwicklung mit Rückkopplungsschleifen zwischen Umsetzung und Prüfung angewendet wird.

// Hinweis: An dieser Stelle bietet sich eine Abbildung des V-Modells (z. B. in Anlehnung an VDI 2206) an, sobald ein Bild bzw. resources/img/placeholder.png vorliegt.
