#import "../../config/acronyms.typ": *
#include "../../config/config.typ"
= Problemstellung
== Einleitung
Die Formula Student ist eine internationale Konstruktionswettbewerbsreihe, in der studentische Teams einen selbst entwickelten Rennwagen entwerfen, fertigen und gegen andere Hochschulteams im Wettbewerb antreten lassen. Neben den klassischen Disziplinen mit fahrergesteuerten Fahrzeugen hat sich in den vergangenen Jahren die Driverless-Klasse etabliert, in der die Fahrzeuge autonom einen zuvor unbekannten, durch Pylonen markierten Kurs abfahren. Die damit verbundenen Aufgaben aus den Bereichen Sensorik, Umfelderkennung, Bahnplanung und Fahrzeugregelung werden in Echtzeit auf einer zentralen Recheneinheit im Fahrzeug ausgeführt.

Das Formula Student Team der #acro("DHBW") Engineering nimmt seit mehreren Saisons an dieser Wettbewerbsreihe teil und entwickelt neben dem mechanischen und elektrischen Fahrzeugaufbau auch das für den fahrerlosen Betrieb erforderliche autonome System. Die zentrale Komponente dieses Systems ist der #acro("DVPC"), der als Recheneinheit die Daten aller Sensoren des autonomen Systems verarbeitet und auf dieser Grundlage die Aktoren des Fahrzeugs ansteuert. Der #acro("DVPC") bildet damit das Bindeglied zwischen der wahrnehmungsseitigen Peripherie und der elektrischen Antriebs- sowie Lenkarchitektur des Rennwagens.

Da sich sowohl das Fahrzeugkonzept als auch die eingesetzte Sensorik und Software zwischen den Saisons weiterentwickeln, unterliegt auch der #acro("DVPC") einem fortlaufenden Anpassungsbedarf. Für die kommende Saison ergeben sich aus einer Überarbeitung des Chassis, einer veränderten Positionierung der Recheneinheit im Fahrzeug sowie gestiegenen Anforderungen an Gewicht und Nutzerfreundlichkeit Rahmenbedingungen, die eine grundlegende Neuentwicklung des #acro("DVPC") erforderlich machen. Die vorliegende Arbeit beschreibt diese Neuentwicklung von der Analyse des Vorjahressystems über die Konzeptphase und die Detailentwicklung der Teilsysteme bis hin zur Integration des Gesamtsystems im Fahrzeug.
