= Abstract

This thesis documents the redesign and integration of the Driverless Vehicle PC (DVPC), the central computing unit of the autonomous system of the Formula Student team DHBW Engineering, for the 2026 season. A change of the vehicle chassis, together with the previous unit's shortcomings in weight and serviceability, required a comprehensive revision of the housing, the cooling system, the electrical interface and the mechanical attachment to the vehicle.

Starting from an analysis of the previous DVPC, requirements were derived for the mechanical, thermal, electronic and usability domains. Several computing platforms and packaging concepts were compared in a prototypical concept phase, leading to the selection of the NVIDIA Jetson Thor as the central computing unit. The reduced power demand and more compact form factor of this platform shaped the subsequent design of the surrounding subsystems.

The selected concept was developed in detail, manufactured and integrated. The casing was realised as an aramid laminate produced with the team's in-house facilities, providing a favourable stiffness-to-weight ratio while avoiding an additional insulating liner. The heatsink was implemented as a selective laser melted aluminium part and integrated in series into the existing battery cooling circuit, removing the need for a dedicated pump and radiator. The mounting was designed as a sheet-metal aluminium part attached to the upper firewall of the rear section, allowing tool-light installation and removal of the unit without disassembling adjacent vehicle components. On the electronic side, a custom DC/DC board based on the TDK-Lambda i7A48020A033V-003-R was designed, assembled and validated under load. System integration covers the mechanical and electrical interconnection of the Jetson Thor, the Lidar PCB and the DCDC board, as well as the provisioning of the six required CAN buses through the on-board headers and an additional four-channel CAN module.

Functional validation was performed in a Hardware-in-the-Loop setup with bench cooling and external power supply. The DVPC was operated for more than one hour under load and in CAN communication without faults, confirming that the requirements are met within the scope tested and clearing the unit for installation in the 2026 season vehicle. Final validation under real operating conditions, a second, weight-optimised heatsink iteration and a possible integration into the team's System Electronics Box remain as follow-up work for subsequent seasons.
