#import "../../config/acronyms.typ": *
#include "../../config/config.typ"

= Zusammenfassung der Ergebnisse
Im Rahmen dieser Arbeit wurde der #acro("DVPC") für die kommende Saison ausgehend von der Analyse des Vorjahressystems und den daraus abgeleiteten Anforderungen (siehe @anforderungen) konstruktiv vollständig neu entwickelt, gefertigt und zu einer funktionsfähigen Einheit integriert. Die Auslegung folgt dem übergeordneten Entwicklungsziel einer konsequenten Gewichtsoptimierung bei gleichzeitiger Erfüllung der mechanischen, thermischen, elektronischen sowie nutzungsseitigen Anforderungen.

In der prototypischen Konzeptentwicklung wurde auf Basis eines direkten Vergleichs zwischen Zotac und Jetson Thor der Jetson Thor als zentrale Recheneinheit festgelegt. Aus dieser Entscheidung resultieren ein deutlich reduzierter Leistungsbedarf an die Spannungsversorgung sowie ein kompakteres Gesamtpackage, die die weitere Konstruktion maßgeblich prägen.

Das Casing wurde als Aramidlaminat ausgeführt (siehe @casingdev) und vollständig mit den Fertigungsmitteln des Vereins hergestellt. Gegenüber einem Alubiegeteil ergeben sich Vorteile in Fertigungsflexibilität, Iterationsgeschwindigkeit und Gewicht, da auf eine isolierende Innenauskleidung verzichtet werden kann. Der Kühlkörper wird in einer ersten, konservativen Iteration als #acro("SLM")-gefertigtes Aluminiumbauteil realisiert und in Reihe in den Batteriekühlkreislauf eingebunden, sodass keine zusätzliche Pumpen- und Radiatorstruktur erforderlich ist. Eine zweite, optimierte Iteration ist konzeptionell vorbereitet.

Das Mounting ist als Alubiegeteil an der oberen Firewall des Hinterwagens ausgeführt (siehe @mounting) und ermöglicht den werkzeugarmen Ein- und Ausbau des Casings, ohne benachbarte Fahrzeugkomponenten zu demontieren. Auf elektronischer Seite wurden eine DCDC-Platine auf Basis des TDK-Lambda i7A48020A033V-003-R für eine Ausgangsleistung von etwa $150 space.thin W$ bei $24 space.thin V$ entworfen, aufgebaut und in einem mehrstufigen Lasttest über mindestens eine Stunde am vorgesehenen Arbeitspunkt validiert (siehe @electronics).

Die Systemintegration (siehe @integration) umfasst die Befestigung von Lidarplatine und DCDC-Platine über Kunststoffstandoffs, die Anbindung des Jetson Thor über drei iterativ angepasste Winkelmountings mit eingepressten M3-Gewinden und Gewindestangen sowie die Konfektionierung der benötigten Ethernet- und #acro("CAN")-Verbindungen. Die sechs am Thor benötigten #acro("CAN")-Busse werden über die zwei direkt am Carrierboard verfügbaren Header sowie ein über einen M.2-Extender robust fixiertes 4-Channel-#acro("CAN")-Modul von PEAK-System bereitgestellt. Ein Tisch-Setup mit eigener Kühlung, Spannungsversorgung und Reservoir erlaubt zusätzlich den Betrieb des #acro("DVPC") außerhalb des Fahrzeugs.

Im abschließenden Integrationstest wurde der #acro("DVPC") im #acro("HiL")-Aufbau mit Tisch-Kühlung und externer Spannungsversorgung über einen Zeitraum von mehr als einer Stunde unter Last sowie im #acro("CAN")-Betrieb fehlerfrei betrieben. Damit liegt ein funktionsfähiges Gesamtsystem vor, das die in @anforderungen formulierten Anforderungen im getesteten Umfang erfüllt und für den Einsatz im Fahrzeug der 26er Saison freigegeben werden kann.
